require:
  - rubocop-github
  - rubocop-rails

inherit_gem:
  rubocop-github:
  - config/default.yml # generic Ruby rules and cops
  - config/rails.yml # Rails-specific rules and cops

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

GitHub/RailsControllerRenderLiteral:
  Enabled: false

GitHub/RailsControllerRenderPathsExist:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
