name: reviewdog

on: [pull_request]

jobs:
  linters:
    name: runner / linters
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-performance:gemfile rubocop-github:gemfile
          reporter: github-pr-review
      - name: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: gemfile
          reporter: github-pr-review
      - name: fasterer
        uses: vk26/action-fasterer@v1
        with:
          reporter: github-pr-review
